app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .models import db, Product

# create a blueprint class, that allows to organize app routes into separate files
bp = Blueprint("routes", __name__)


# define a route for the main page
@bp.route("/")
def index():
    # return the html file for page
    return render_template("index.html")


@bp.route("/contacts")
def contacts():
    return render_template("contacts.html")


@bp.route("/products")
def products():
    # gets products from database
    products = Product.query.all()
    # render product_list.html
    return render_template("products_list.html", products=products)


# route for page and request to add a new product
@bp.route("/add", methods=["GET", "POST"])
def add_product():
    # if method type is post, then add a new product
    if request.method == "POST":

        # get data from form and save them in variables
        name = request.form["name"]
        price = request.form["price"]

        description = request.form["description"]
        stock = int(request.form["stock"])
        is_active = request.form.get("is_active") == "on"
        category = request.form["category"]
        rating = float(request.form["rating"])
        sale = request.form.get("sale") == "on"

        print (f'''[DEBUG]: name={name}, price={price}, description={description}, stock={stock}, is_active={is_active}, category={category}, rating={rating}, sale={sale}''')

        # create a new product class
        product = Product(
            name=name,
            price=float(price),
            description=description,
            stock=int(stock),
            is_active=is_active,
            category=category,
            rating=float(rating),
            sale=sale,
        )
        # add product to db
        db.session.add(product)
        # commit changes
        db.session.commit()

        # show message, that product was added
        flash("Product added!")
        # redirect to products page
        return redirect(url_for("routes.products"))
    # if method type is get, then render page with variables action and product
    return render_template("product_form.html", action="Add", product=None)

# route for deleting a product
# <int:product_id> - <type of variable:name variable>
@bp.route("/delete/<int:product_id>", methods=["POST"])
def delete_product(product_id):
    # finding by product_id a product from a database, if not exist - redirect to a 404 error (not founded) page
    product = Product.query.get_or_404(product_id)
    # delete a product from database
    db.session.delete(product)
    # committing a change
    db.session.commit()
    flash("Product deleted!")
    # redirect user to products page
    return redirect(url_for("routes.products"))

# route for updating a product info
# <int:product_id> - <type of variable:name variable>
@bp.route("/update/<int:product_id>", methods=["GET", "POST"])
def update_product(product_id):
    # finding by product_id a product from a database, if not exist - redirect to a 404 error (not founded) page
    product = Product.query.get_or_404(product_id)
    # if method is "POST" - update values in database
    if request.method == "POST":
        # getting values from form
        product.name = request.form["name"]
        product.price = float(request.form["price"])

        product.description = request.form["description"]
        product.stock = int(request.form["stock"])
        product.is_active = request.form.get("is_active") == "on"
        product.category = request.form["category"]
        product.rating = float(request.form["rating"])
        product.sale = request.form.get("sale") == "on"

        print (f'''[DEBUG]: name={product.name}, price={product.price}, description={product.description}, stock={product.stock}, is_active={product.is_active}, category={product.category}, rating={product.rating}, sale={product.sale}''')

        # committing a change
        db.session.commit()
        flash("Product updated!")
        # redirect to a products page
        return redirect(url_for("routes.products"))
    # if method is "GET" - render a page product_form with product info
    return render_template("product_form.html", action="Update", product=product)

templates/contacts.html
<!DOCTYPE html>
<html>
    <head>
        <title>PhoneStore | Контактна інформація</title>
        <link rel="stylesheet" href="../static/style.css">
    </head>
    <body>
        <h1>Контактна інформація</h1>
        <ul>
            <li>Номер телефону: +380 (12) 345 67 89</li>
            <li>Адреса: Житомир, вулиця Лесі Українки, 76 / Zhytomyr, Lesia Ukrainka Street, 67</li>
            <li>ТОВ «Zhytomyr PhoneStore»</li>
        </ul>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>PhoneStore</title>
        <link rel="stylesheet" href="../static/style.css">
    </head>
    <body>
        <h1>Онлайн-магазин</h1>
        <a href="products">Продукти</a>
    </body>
</html>

templates/product_form.html
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PhoneStore | {{action}} Product</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/style.css">
</head>

<body>

    <div class="form container">
        <form method="post">

            <h1>{{action}} Product</h1>

            <div class="input-group mb-3">
                <span class="input-group-text">Name</span>
                <input type="text" placeholder="iPhone 21" name="name" value="{{product.name if product else ''}}"
                    required aria-label="Name" class="form-control">
                <span class="input-group-text">Category</span>
                <input class="form-control" list="categoryOptions" type="text" name="category"
                    value="{{product.category if product else ''}}">
                <datalist id="categoryOptions">
                    <option value="Apple">
                    <option value="Samsung">
                    <option value="Nothing">
                    <option value="Google Pixel">
                    <option value="Xiaomi">
                </datalist>
            </div>

            <div class="input-group mb-3">
                <span class="input-group-text">Price</span>
                <input class="form-control" type="number" name="price" step="0.01"
                    value="{{product.price if product else 0}}" required min="0">
                <span class="input-group-text">₴</span>

                <span class="input-group-text">Stock</span>
                <input class="form-control" type="number" name="stock" step="1"
                    value="{{product.stock if product else 0}}" min="0">
            </div>


            <div class="input-group mb-3">
                <span class="input-group-text">Description</span>
                <textarea class="form-control" rows="3" name="description">{{product.description if product else ''}}</textarea>
            </div>

            <div class="mb-3">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="is_active" name="is_active" {% if product and
                        product.is_active %}checked{% endif %}>
                    <label class="form-check-label" for="is_active">Is Active?</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="sale" id="sale" {% if product and product.sale
                        %}checked{% endif %}>
                    <label class="form-check-label" for="sale">On Sale?</label>
                </div>
            </div>

            <div class="mb-3">
                <label for="rating" class="form-label">Rating</label>
                <output for="rating" id="ratingValue" aria-hidden="true"></output>
                <input type="range" id="rating" class="form-range" name="rating" step="0.1" min="0" max="5"
                    value="{{product.rating if product else 0}}">

                <script>
                    // This is an example script, please modify as needed
                    const ratingInput = document.getElementById('rating');
                    const ratingOutput = document.getElementById('ratingValue');

                    ratingOutput.textContent = ratingInput.value + " ⭐";

                    ratingInput.addEventListener('input', function () {
                        ratingOutput.textContent = this.value + " ⭐";
                    });
                </script>
            </div>


            <button type="submit" class="btn btn-primary">{{action}}</button>
            <a class="btn btn-secondary" href="{{url_for('routes.products')}}" role="button">Back to the list</a>


        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/products_list.html
<!DOCTYPE html>
<html>

<head>
    <title>PhoneStore | Список продуктів</title>
    <link rel="stylesheet" href="../static/style.css">
</head>

<body>
    <h1>Список продуктів</h1>

    <!-- link to add product page -->
    <a href="{{ url_for('routes.add_product') }}">Add Product</a>

    <table border="1">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Stock</th>
            <th>Is Active</th>
            <th>Category</th>
            <th>Rating</th>
            <th>Sale</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Edit</th>
        </tr>
        {% for product in products %}
        <tr>
            <td>{{product.id}}</td>
            <td>{{product.name}}</td>
            <td>{{product.price}}</td>
            <td>{{product.description}}</td>
            <td>{{product.stock}}</td>
            <td>{{product.is_active}}</td>
            <td>{{product.category}}</td>
            <td>{{product.rating}}</td>
            <td>{{product.sale}}</td>
            <td>{{product.created_at}}</td>
            <td>{{product.updated_at}}</td>
            <td>
                <a href="{{ url_for('routes.update_product', product_id=product.id) }}">Edit</a>
                <form action="{{ url_for('routes.delete_product', product_id=product.id) }}" method="post"
                    style="display:inline;">
                    <button type="submit">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>

</body>

</html>